amp: false
batch_size: 5000
bert: xlm-roberta-large
bert_pad_index: null
bert_pooling: mean
binarize: false
bos_index: 0
buckets: 32
build: true
cache: false
char_pad_index: null
checkpoint: false
clip: 5.0
delete: !!set
  ? ''
  : null
  '!': null
  '''''': null
  ',': null
  -NONE-: null
  .: null
  ':': null
  '?': null
  S1: null
  TOP: null
  '``': null
dev: /home/wolfingten/projects/data/tut/combined.val
device: '0'
dist: ddp
embed: glove-6b-100
encoder: bert
encoder_dropout: 0.1
eos_index: 2
epochs: 10
equal:
  ADVP: PRT
even: false
feat: null
fix_len: 20
implicit: false
local_rank: 0
lr: 5.0e-05
lr_rate: 20
max_len: null
mbr: false
min_freq: 2
mix_dropout: 0.0
mlp_dropout: 0.33
mode: train
n_bert_layers: 4
n_chars: null
n_label_mlp: 100
n_labels: 789
n_span_mlp: 500
n_tags: null
n_words: 250002
pad_index: 1
path: model
patience: 100
seed: 1
steps: 130
test: /home/wolfingten/projects/data/tut/combined.test
threads: 16
train: /home/wolfingten/projects/data/tut/combined.train
unk_index: 3
update_steps: 4
verbose: true
wandb: false
warmup: 0.1
workers: 0
